import { emailTemplateFactory } from "./email-factory";
import AnnouncementEmailTemplate from "./templates/AnnouncementEmail";
export const AnnouncementEmail = emailTemplateFactory(AnnouncementEmailTemplate);
import BaseEmailTemplateTemplate from "./templates/BaseEmailTemplate";
export const BaseEmailTemplate = emailTemplateFactory(BaseEmailTemplateTemplate);
import CertificateExpirationWarningEmailTemplate from "./templates/CertificateExpirationWarningEmail";
export const CertificateExpirationWarningEmail = emailTemplateFactory(CertificateExpirationWarningEmailTemplate);
import CertificateExpiredEmailTemplate from "./templates/CertificateExpiredEmail";
export const CertificateExpiredEmail = emailTemplateFactory(CertificateExpiredEmailTemplate);
import CourseDueDateReminderEmailTemplate from "./templates/CourseDueDateReminderEmail";
export const CourseDueDateReminderEmail = emailTemplateFactory(CourseDueDateReminderEmailTemplate);
import CoursePaymentSucceededEmailTemplate from "./templates/CoursePaymentSucceededEmail";
export const CoursePaymentSucceededEmail = emailTemplateFactory(CoursePaymentSucceededEmailTemplate);
import CreatePasswordReminderEmailTemplate from "./templates/CreatePasswordReminderEmail";
export const CreatePasswordReminderEmail = emailTemplateFactory(CreatePasswordReminderEmailTemplate);
import FinishedCourseEmailTemplate from "./templates/FinishedCourseEmail";
export const FinishedCourseEmail = emailTemplateFactory(FinishedCourseEmailTemplate);
import LiveTrainingEndedEmailTemplate from "./templates/LiveTrainingEndedEmail";
export const LiveTrainingEndedEmail = emailTemplateFactory(LiveTrainingEndedEmailTemplate);
import LiveTrainingReminderEmailTemplate from "./templates/LiveTrainingReminderEmail";
export const LiveTrainingReminderEmail = emailTemplateFactory(LiveTrainingReminderEmailTemplate);
import LiveTrainingStartedEmailTemplate from "./templates/LiveTrainingStartedEmail";
export const LiveTrainingStartedEmail = emailTemplateFactory(LiveTrainingStartedEmailTemplate);
import MagicLinkEmailTemplate from "./templates/MagicLinkEmail";
export const MagicLinkEmail = emailTemplateFactory(MagicLinkEmailTemplate);
import NewUserEmailTemplate from "./templates/NewUserEmail";
export const NewUserEmail = emailTemplateFactory(NewUserEmailTemplate);
import OverdueCoursesEmailTemplate from "./templates/OverdueCoursesEmail";
export const OverdueCoursesEmail = emailTemplateFactory(OverdueCoursesEmailTemplate);
import PasswordRecoveryEmailTemplate from "./templates/PasswordRecoveryEmail";
export const PasswordRecoveryEmail = emailTemplateFactory(PasswordRecoveryEmailTemplate);
import UserAssignedToCourseEmailTemplate from "./templates/UserAssignedToCourseEmail";
export const UserAssignedToCourseEmail = emailTemplateFactory(UserAssignedToCourseEmailTemplate);
import UserFinishedChapterEmailTemplate from "./templates/UserFinishedChapterEmail";
export const UserFinishedChapterEmail = emailTemplateFactory(UserFinishedChapterEmailTemplate);
import UserFinishedCourseEmailTemplate from "./templates/UserFinishedCourseEmail";
export const UserFinishedCourseEmail = emailTemplateFactory(UserFinishedCourseEmailTemplate);
import UserFirstLoginEmailTemplate from "./templates/UserFirstLoginEmail";
export const UserFirstLoginEmail = emailTemplateFactory(UserFirstLoginEmailTemplate);
import UserInviteEmailTemplate from "./templates/UserInviteEmail";
export const UserInviteEmail = emailTemplateFactory(UserInviteEmailTemplate);
import UserLongInactivityEmailTemplate from "./templates/UserLongInactivityEmail";
export const UserLongInactivityEmail = emailTemplateFactory(UserLongInactivityEmailTemplate);
import UserShortInactivityEmailTemplate from "./templates/UserShortInactivityEmail";
export const UserShortInactivityEmail = emailTemplateFactory(UserShortInactivityEmailTemplate);
import WelcomeEmailTemplate from "./templates/WelcomeEmail";
export const WelcomeEmail = emailTemplateFactory(WelcomeEmailTemplate);
export { getCourseDueDateReminderEmailTranslations } from "./translations/courseDueDateReminder";